### ISSUE TITLE
Matching less granuarly

### ISSUE THREAD

**Issue by asmodeus812** [yorickpeterse/nvim-tree-pairs#4]
Hi, i was wondering if there is a plan to provide an exclusion for certain `low` level type of nodes such as identifiers, as it is right now if i have the following 

```java
public static void main() {
}
```

And cursor is on the `p` in public, it would jump to the `c` in the word static. However by default matchit would be less fine grained, and jump to the brackets, would it be possible to configure the granularity of pairing ?

**Comment by yorickpeterse** [comment]
This requires language specific query files, as the rules between languages and their syntax elements differs greatly. https://github.com/theHamsta/nvim-treesitter-pairs takes this approach, but it requires maintaining a large set of query files which I'm not interested in :smiley:
